### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by guixinyang** [Kr1S-D/UltimateAntibotRecoded#1]
[17:02:35 ERROR]: Error occurred while enabling UltimateAntiBot v4.0.0-ABYSS (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.kr1s_d.ultimateantibot.common.helper.LogHelper.error(String)" because "this.logHelper" is null
        at me.kr1s_d.ultimateantibot.UltimateAntiBotSpigot.onEnable(UltimateAntiBotSpigot.java:71) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:02:35 INFO]: [UltimateAntiBot] Disabling UltimateAntiBot v4.0.0-ABYSS
[17:02:35 ERROR]: Error occurred while disabling UltimateAntiBot v4.0.0-ABYSS (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.kr1s_d.ultimateantibot.common.helper.LogHelper.info(String)" because "this.logHelper" is null
        at me.kr1s_d.ultimateantibot.UltimateAntiBotSpigot.onDisable(UltimateAntiBotSpigot.java:142) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Kr1S-D** [comment]
Seems to be a configuration error, Did you delete the plugin files before updating the plugin?

**Comment by guixinyang** [comment]
Sorry, I didn't delete the configuration file After deletion, it will return to normal

**Comment by Kr1S-D** [comment]
Perfetct 👍
