### ISSUE TITLE
Exception executing uab check on console

### ISSUE THREAD

**Issue by a1375625918** [Kr1S-D/UltimateAntibotRecoded#16]
```
>uab check 6a8a2a07
[17:57:33] [Server thread/INFO]: BLACKLIST INFO:
[17:57:33] [Server thread/INFO]:
[17:57:33] [Server thread/INFO]: Reason ? An administrator blacklisted you
[17:57:33] [Server thread/INFO]: IP ? 192.168.1.1
[17:57:33] [Server thread/INFO]: NickName ? _NAME_NOT_FOUND_
[17:57:33] [Server thread/INFO]: ID ? 6a8a2a07
[17:57:33] [Server thread/INFO]:
[17:57:33] [Server thread/WARN]: Unexpected exception while parsing console command "uab check 6a8a2a07"
org.bukkit.command.CommandException: Unhandled exception executing command 'uab' in plugin UltimateAntiBot v4.0.5-ABYSS
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:847) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3634-Spigot-d90018e-397c555]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3634-Spigot-d90018e-397c555]
        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:413) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3634-Spigot-d90018e-397c555]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3634-Spigot-d90018e-397c555]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1201) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3634-Spigot-d90018e-397c555]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3634-Spigot-d90018e-397c555]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3634-Spigot-d90018e-397c555]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.command.ColouredConsoleSender cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_19_R2.command.ColouredConsoleSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @4678c730)
        at me.kr1s_d.ultimateantibot.commands.CheckIDCommand.execute(CheckIDCommand.java:59) ~[?:?]
        at me.kr1s_d.commandframework.CommandManager.onCommand(CommandManager.java:62) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

**Comment by Kr1S-D** [comment]
Who sent the command? Was it a player or did you do it through something else?

**Comment by a1375625918** [comment]
On console. The black cmd window running the server software.

**Comment by Kr1S-D** [comment]
ok thx it will be fixed in the new version
