### ISSUE TITLE
Exception during loading while blacklist.yml is ~4MB

### ISSUE THREAD

**Issue by pionner121** [Kr1S-D/UltimateAntibotRecoded#21]
Hi,
I got exception below while loading UAB on Waterfall while my blacklist reached about 3.7MB. UAB then disabled itself.
After deleting blacklist.yml it loaded without any problems.
Possible fix: split file when reaching YAML document limit into several files.
Thanks!

> [02:30:12] [main/WARN]: Exception encountered when loading plugin: UltimateAntiBot
org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:342) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:694) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:239) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:208) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:347) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:332) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:134) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:160) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:470) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:112) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:80) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:72) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at me.kr1s_d.ultimateantibot.objects.Config.getConfiguration(Config.java:39) ~[?:?]
	at me.kr1s_d.ultimateantibot.objects.Config.<init>(Config.java:32) ~[?:?]
	at me.kr1s_d.ultimateantibot.UltimateAntiBotBungeeCord.onEnable(UltimateAntiBotBungeeCord.java:70) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]

**Comment by Kr1S-D** [comment]
Hello, sorry for delayed answer, i suggest you to clear the file regenerating it

**Comment by pionner121** [comment]
> Hello, sorry for delayed answer, i suggest you to clear the file regenerating it

I did, however that doesn't fix underlying problem, as for my understanding large blacklist can exceed the limit and WILL happen again given enough time (sooner on large servers).
As per exception "The incoming YAML document exceeds the limit: 3145728 code points.". It seems you're hitting YAML library hard limit.
