### ISSUE TITLE
antivpn error

### ISSUE THREAD

**Issue by yuankun1** [Kr1S-D/UltimateAntibotRecoded#34]
I don't know if the VPN I hung up caused my server TPS to become 15 and then the collective players dropped
I put on the report I served by the way spark
https://spark.lucko.me/bgZ8Yz2l6m
 java.net.ConnectException: Connection timed out: connect
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.DualStackPlainSocketImpl.connect0(Native Method)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:75)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.Socket.connect(Socket.java:606)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.Socket.connect(Socket.java:555)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.http.HttpClient.openServer(HttpClient.java:499)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.http.HttpClient.openServer(HttpClient.java:594)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.http.HttpClient.<init>(HttpClient.java:278)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.http.HttpClient.New(HttpClient.java:375)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.http.HttpClient.New(HttpClient.java:393)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1240)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:995)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.net.URL.openStream(URL.java:1092)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at me.kr1s_d.ultimateantibot.common.antivpn.ipapi.IPAPIProvider.getResults(IPAPIProvider.java:51)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at me.kr1s_d.ultimateantibot.common.antivpn.ipapi.IPAPIProvider.process(IPAPIProvider.java:29)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at me.kr1s_d.ultimateantibot.common.service.VPNService.lambda$submitIP$1(VPNService.java:59)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:32:20] [Craft Scheduler Thread - 228/WARN]:         at java.lang.Thread.run(Thread.java:750)
![spark](https://github.com/Kr1S-D/UltimateAntibotRecoded/assets/19505154/511b4a2f-fd33-420e-9a23-72bb1859ac3e)

**Comment by Kr1S-D** [comment]
The http queries are carried out asynchronously, I see it as difficult, which caused the crash, the only possibility is the following: the machine on which the server is present is not very powerful and following an attack it loaded too much and therefore the operating system itself was unable to maintain the load of operations as the Minecraft thread took up too much and therefore the asynchronous threads were slowed down in turn giving this error
