### ISSUE TITLE
Support folia

### ISSUE THREAD

**Issue by RanMinecraft** [Kr1S-D/UltimateAntibotRecoded#35]
https://github.com/PaperMC/Folia

**Comment by Kr1S-D** [comment]
the plugin should support basic folia but I'm not sure, could you test?

**Comment by xyfwdy** [comment]
> the plugin should support basic folia but I'm not sure, could you test?

Its not support right now , All bukkit scheduler need to replace.

**Comment by Kr1S-D** [comment]
Hi, I saw your pull-request, I will manually apply the change to the code (leave it open for now, at most I'll close it myself) as I prefer to create another specific module for folia support for a question of organization of the code that I want to keep in the project in order to make it simple to operate and in case of specific bugs on folia not to modify the entire bukkit code, thank you very much anyway for creating those classes from which I will draw inspiration to create the final class, unfortunately I can't test the plugin if you want to do it I would be very grateful, let me know

**Comment by lokspel** [comment]
[22:56:22 ERROR]: [DirectoryProviderSource] Error loading plugin: Could not load plugin 'UltimateAntiBot v4.1.2-ABYSS' as it is not marked as supporting Folia!
java.lang.RuntimeException: Could not load plugin 'UltimateAntiBot v4.1.2-ABYSS' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:40) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:28) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:72) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:95) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:63) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at net.minecraft.server.Main.main(Main.java:108) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at org.bukkit.craftbukkit.Main.main(Main.java:240) ~[foldenor-1.21.11.jar:1.21.11-DEV-f9c85e5]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]
